### ISSUE TITLE
Undefined symbols for architecture armv7: "_glu*"

### ISSUE THREAD

**Issue by eswick** [p3/regal#162]
I built the Regal static library for iOS using Xcode. However, upon linking my project, `_gluBuild2DMipmaps` and `_gluOrtho2D` are undefined by the linker.

Are the GLU functions implemented on iOS? If so, any idea why they aren't present in libRegal.a?

**Comment by nigels-com** [comment]
Regal does not provide GLU entry points.  Is there a GLU library target in the XCode project?  Try building and linking that too.

**Comment by eswick** [comment]
Are you sure? There is RegalGLU.h which contains definitions for the function.

I added files from the libutil directory to the default target and it appears to have worked. I think libutil should be included in the project by default, it may be a mistake.

**Comment by nigels-com** [comment]
To clarify:
GLU is not an OpenGL API.  It's a library layered on top of OpenGL.
RegalGLU is a build of GLU that depends on Regal, rather than the usual OpenGL.

**Comment by eswick** [comment]
I will fork Regal and add an Xcode target for RegalGLU.
