### ISSUE TITLE
Assertion Failed: max_vertex_attribs >= 8

### ISSUE THREAD

**Issue by eswick** [p3/regal#163]
When trying to use Regal on an iPhone 6, iOS 9.0.2, the following assertion fails:
Assertion Failed: /Users/eswick/Development/regal/src/regal/RegalVao.h 178: max_vertex_attribs >= 8

Any ideas why this is happening?

**Comment by nigels-com** [comment]
Is there a valid (ES2?) context when this check is made?

**Comment by eswick** [comment]
Ah, yes, that was the issue.
I was calling RegalMakeCurrent only, without calling [EAGLContext setCurrentContext:]

Thank you for your help!
